// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHZEmMfniClW5_QqdPN_Dqhphgc7ci3M',
    appId: '1:727161401500:web:c588e8b9091ac33d7afd59',
    messagingSenderId: '727161401500',
    projectId: 'erickfy-877d6',
    authDomain: 'erickfy-877d6.firebaseapp.com',
    storageBucket: 'erickfy-877d6.firebasestorage.app',
    measurementId: 'G-C55GDWQGC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauSKzs8z3Rd62kJxF5z-v38TkuKWTruY',
    appId: '1:727161401500:android:b7f2e2c2e5de2dd57afd59',
    messagingSenderId: '727161401500',
    projectId: 'erickfy-877d6',
    storageBucket: 'erickfy-877d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbuFwWOipiN7-01dKIEJkN5nVLY6i11sM',
    appId: '1:727161401500:ios:4194ea06dfb1421c7afd59',
    messagingSenderId: '727161401500',
    projectId: 'erickfy-877d6',
    storageBucket: 'erickfy-877d6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbuFwWOipiN7-01dKIEJkN5nVLY6i11sM',
    appId: '1:727161401500:ios:4194ea06dfb1421c7afd59',
    messagingSenderId: '727161401500',
    projectId: 'erickfy-877d6',
    storageBucket: 'erickfy-877d6.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMHZEmMfniClW5_QqdPN_Dqhphgc7ci3M',
    appId: '1:727161401500:web:a5ab82f67cb456917afd59',
    messagingSenderId: '727161401500',
    projectId: 'erickfy-877d6',
    authDomain: 'erickfy-877d6.firebaseapp.com',
    storageBucket: 'erickfy-877d6.firebasestorage.app',
    measurementId: 'G-D6E73G37DG',
  );
}
